{{- if and .Values.credentials.agentToken (not .Values.credentials.existingSecret) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "opsscript-agent.credentialsSecretName" . }}
  labels:
    {{- include "opsscript-agent.labels" . | nindent 4 }}
type: Opaque
stringData:
  AGENT_TOKEN: {{ .Values.credentials.agentToken | quote }}
{{- end }}
