# Default values for dumpscript

image:
  # Image repository
  repository: ghcr.io/cloudscript-technology/dumpscript
  # Image pull policy
  pullPolicy: IfNotPresent
  # Image tag. Default is the chart appVersion
  tag: ""

# Image pull secrets
imagePullSecrets: []

# Override the name of the chart
nameOverride: ""

# Override the full name of the chart
fullnameOverride: ""

databases:
  - type: postgresql
    # Version of the PostgreSQL client (13, 14, 15, 16, 17)
    # This version should match your PostgreSQL server version to avoid compatibility issues
    version: "17"
    # Backup periodicity: daily, weekly, monthly, yearly
    periodicity:
    - type: daily
      retentionDays: 7
      schedule: "0 1 * * *" # Every day at 1am
    - type: weekly
      retentionDays: 30
      schedule: "0 2 * * *" # Every day at 2am
    - type: monthly
      retentionDays: 365
      schedule: "0 3 * * *" # Every day at 3am
    # Database connection information
    connectionInfo:
      # Database host (if secretName is not provided)
      host: ""
      # Database username (if secretName is not provided)
      username: ""
      # Database password (if secretName is not provided)
      password: ""
      # Database name (if secretName is not provided)
      database: ""
      # Database port (if secretName is not provided)
      port: 5432
      # Name of the secret containing the connection information for the database
      secretName: ""
    aws:
      # AWS region for the S3 bucket
      region: ""
      # AWS bucket to store the database dump
      bucket: ""
      # Prefix for the database dump in the S3 bucket
      bucketPrefix: ""
      # Name of the secret containing the AWS credentials
      secretName: ""
    # Extra arguments for the database dump (e.g. --encoding=utf8, --no-owner)
    extraArgs: ""
  - type: mysql
    # Version of the MySQL/MariaDB client (8.0, 10.11, 11.4)
    # - Use "8.0" for MySQL 8.0
    # - Use "10.11" for MariaDB 10.11 (default)
    # - Use "11.4" for MariaDB 11.4
    version: "10.11"
    # Backup periodicity: daily, weekly, monthly, yearly
    periodicity:
    - type: daily
      retentionDays: 7
      schedule: "0 1 * * *" # Every day at 1am
    - type: weekly
      retentionDays: 30
      schedule: "0 2 * * *" # Every day at 2am
    - type: monthly
      retentionDays: 365
      schedule: "0 3 * * *" # Every day at 3am
    # Database connection information
    connectionInfo:
      # Database host (if secretName is not provided)
      host: ""
      # Database username (if secretName is not provided)
      username: ""
      # Database password (if secretName is not provided)
      password: ""
      # Database name (if secretName is not provided)
      database: ""
      # Database port (if secretName is not provided)
      port: 3306
      # Name of the secret containing the connection information for the database
      secretName: ""
    aws:
      # AWS region for the S3 bucket
      region: ""
      # AWS bucket to store the database dump
      bucket: ""
      # Prefix for the database dump in the S3 bucket
      bucketPrefix: ""
      # Name of the secret containing the AWS credentials
      secretName: ""
    # Extra arguments for the database dump (e.g. --single-transaction, --routines)
    extraArgs: ""

notifications:
  slack:
    # Enable Slack notifications
    enabled: false
    # Slack webhook URL
    webhookUrl: ""
    # Slack channel (optional)
    channel: ""
    # Slack username (optional)
    username: ""
    # Notify on success
    notifyOnSuccess: false

serviceAccount:
  # Create a service account
  create: true
  # Automount service account token
  automount: true
  # Annotations for the service account
  annotations: {}
  # Name of the service account
  name: ""
  # Namespace for the service account. Required if create=true
  namespace: "" 

# Annotations for the pod
podAnnotations: {}

# Labels for the pod
podLabels: {}

# Security context for the pod
podSecurityContext: {}
  # fsGroup: 2000

# Security context for the container
securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

# Resource requests and limits for the container
resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

# Node selector for the pod
nodeSelector: {}

# Tolerations for the pod
tolerations: []

# Affinity rules for the pod
affinity: {}

# IMPORTANT: We recommend using a emptyDir volume to store the database dump if the database is too large

# Extra volumes for the pod
extraVolumes: []
# extraVolumes:
#   - name: "data"
#     emptyDir:
#       sizeLimit: "30Gi"

# Extra volume mounts for the pod
extraVolumeMounts: []
# extraVolumeMounts:
#   - name: "data"
#     mountPath: "/dumpscript"
#     readOnly: false