{{- range $app := .Values.apps }}
{{- if and $app.enabled $app.secrets }}
{{- if and $app.secrets.external $app.secrets.external.enabled }}
{{- range $secret := $app.secrets.external.items }}
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "deploy-apps.app.externalSecretName" (dict "root" $ "app" $app "secret" $secret) }}
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "deploy-apps.app.labels" (dict "root" $ "app" $app) | nindent 4 }}
spec:
  refreshInterval: {{ $secret.refreshInterval | default "1h" }}
  secretStoreRef:
    name: {{ $secret.secretStoreRef.name }}
    kind: {{ $secret.secretStoreRef.kind | default "SecretStore" }}
  target:
    {{- if and $secret.target $secret.target.name }}
    name: {{ $secret.target.name }}
    {{- else }}
    name: {{ include "deploy-apps.app.externalSecretName" (dict "root" $ "app" $app "secret" $secret) }}
    {{- end }}
    creationPolicy: {{ $secret.creationPolicy | default "Owner" }}
    {{- if $secret.template }}
    template:
      {{- toYaml $secret.template | nindent 6 }}
    {{- end }}
  {{- if $secret.data }}
  data:
    {{- toYaml $secret.data | nindent 4 }}
  {{- end }}
  {{- if $secret.dataFrom }}
  dataFrom:
    {{- toYaml $secret.dataFrom | nindent 4 }}
  {{- end }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}
