apiVersion: v2
name: deploy-apps
description: Helm chart flexível para deploy de múltiplas aplicações (Deployment, StatefulSet, CronJob, Job) com suporte a External Secrets e KEDA
type: application
version: 0.1.10
appVersion: "0.1.10"
kubeVersion: ">= 1.27.0-0"
home: https://cloudscript.com.br
icon: https://charts.cloudscript.com.br/helm-charts/deploy-apps/cloudscript-logo.png
keywords:
  - kubernetes
  - helm
  - multi-app
  - deployment
  - statefulset
  - cronjob
  - job
  - external-secrets
  - keda
  - autoscaling
  - cloudscript
maintainers:
  - name: Jonathan Schmitt
    email: jonathan.schmitt@cloudscript.com.br
dependencies: []
annotations:
  artifacthub.io/changes: |
    - kind: added
      description: Support for metadata annotations on Job resources (useful for ArgoCD hooks)
  artifacthub.io/displayName: "Deploy Apps"
  artifacthub.io/license: "Apache-2.0"
  artifacthub.io/provider: "Cloudscript"
  artifacthub.io/links: |
    - name: Cloudscript
      url: https://cloudscript.com.br
    - name: Documentation
      url: https://github.com/cloudscript-technology/helm-charts/tree/main/deploy-apps
